[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["hnOsmium0001 <36975818+hnOsmium0001@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
